title: HRP Portfolio Optimization
description: Hierarchical Risk Parity Project by Dr. Athar Kharal
theme: minima
markdown: kramdown
include:
  - index.md
  - theory.md
  - implementation.md
  - applications.md
